### ISSUE TITLE
GTX 1650(TU117) was castrated

### ISSUE THREAD

**Issue by aliofwind** [rigaya/NVEnc#114]
From NVIDIA:
https://www.nvidia.com/en-us/geforce/graphics-cards/gtx-1650/
![image](https://user-images.githubusercontent.com/35068322/56630515-36a4d880-6684-11e9-97eb-2601b86128ef.png)
https://developer.nvidia.com/video-encode-decode-gpu-support-matrix#Encoder
![image](https://user-images.githubusercontent.com/35068322/56630523-3f95aa00-6684-11e9-8191-03ebc022cae7.png)
GTX 1650 uses Volta NVENC, and doesn't support HEVC B frame.

**Comment by PhoO3nX** [comment]
Ok but where is the issue ? You can close... 

Buy a 1660/Ti offer B Frames support but not the low cost xx50 family...  (low cost cards can have less shaders, GDDR3, etc...)

Blame nvidia, NVEnc can do nothing for you unfortunaly

**Comment by hydra3333** [comment]
>  where is the issue

The issue is most people wouldn't know about it and may have been "conned" by fancy new product version numbering.  

Thanks for the info aliofwind, I learned of the info from you.

It seems similar to the 1060 3Gb which had a crippled (i.e. actually lesser) number of cores compared to the 1060 6Gb version ... people may have been "conned" into thinking they were one and the same when they were not.  

Naughty manufacturer.
