### ISSUE TITLE
Looking for the absolute maximum quality achievable by a GTX 1080

### ISSUE THREAD

**Issue by pwacooijmans** [rigaya/NVEnc#166]
using ffms2 version 2.23 maybe I need to update this but for now I can make 12 bits videos with it.
using avisynth+
using staxrip newest version (beta) 2.0.4.10
Videodriver 440.97
these are my compression settings....I can NOT change vbr to vbr-hq since it will go over 25000kilobits per second which is the limit of my tv for hevc 4k hdr. Neither can I change the 40000kilobit max-bitrate same reason....nor can I change the vbv-bufsize else it won't be hdr.
--vbr 25000 --codec h265 --preset quality --profile main10 --tier high --output-depth 10 --max-bitrate 40000 --vbv-bufsize 160000 --aq --bframes 0 --lookahead 32 --no-b-adapt --no-i-adapt --cuda-schedule auto --output-buf 128 --master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,0)" --videoformat pal --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --max-cll "1000,640" --chromaloc 2 --mv-precision q-pel

If someone knows a setting to improve quality with the limitations I have given I will be very happy.
The settings I gave are for the movie La La Land (2016) just as an example. Videoformat Pal I use just because my TV doesn't understand undefined.

**Comment by zerowalkx** [comment]
hello dont use staxrip ...

**Comment by Starkler** [comment]
> 
> 
> hello dont use staxrip ...

It is better to use Hybrid.

**Comment by ls-milkyway** [comment]
Some x264 commands cannot work with nvencc because it strictly close to the commands available with nvidia hardware...check nividia encoding guide. It will bound to fail or throw errors.

If want to make your encodes compatible with your TV then use CQP option instead of VBR ...of-course you will loose some quality there but some of it can be adjusted  using sharp and contrast enhancement.

I have done extensive research using both HYBRID & STAXRIP and found that STAXRIP is not only more stable than HYBRID but produces better quality encodes using the same x264 available settings plus STAXRIP has beautiful way of fine-tuning the video using VPP options..(compared them using VMAF SSIM and other qualty metrics).
