### ISSUE TITLE
Option to ignore options that would lead the encode to fail

### ISSUE THREAD

**Issue by warrex1979** [rigaya/NVEnc#176]
This is a **feature request**:

Can we have an option to tell NVEncC to ignore options that it knows would lead the encode to fail and instead have it just output warnings that these options where dropped? E.g. --vpp-subburn track=3 will lead the encode to fail if there is no corresponding subtitle track.

ffmpeg has something roughly similar for tracks:

> To map the video and audio streams from the first input, and using the trailing ?, ignore the audio mapping if no audio streams exist in the first input:
ffmpeg -i INPUT -map 0:v -map 0:a? OUTPUT

This is for example useful to run the same command over several structurally similar files.

**Comment by ls-milkyway** [comment]
Yep, if you mention wrong subtitle track...it will fail to encode with reason in the log file....you will also have to enter the command in detail for eg. "track=3,charcode=utf-8,shaping=complex" for subtitles to be hard coded properly if you are using ass file instead of simple srt file..etc.

 I am afraid nvencc being a command line app is not meant for casual encoders ...you will have to dwell deep ...plz read its manual carefully and then try to implement ..it simply behaves like GIGO (garbage in garbage out)...but is very efficient and powerful tool for quality encodes using nvidia cards.
If you have many files (with subtitles in some) and want to run nvencc command over all of them, then you will have to use a DOS script to read which of them have subtitles ...and create the code to pass that parameter to nvencc command....

**Comment by rigaya** [comment]
I've checked other options like --audio-codec / --sub-codec. When the specified track does not exist in the input file, these options were showing warnings but the encode process continues which I think is the behavior you expect.

I thought it would then be fine for "--vpp-subburn track=n" to have the same behavior. I've changed the behavior of --vpp-subburn track=n in [NVEnc 4.60](https://github.com/rigaya/NVEnc/releases/tag/4.60), now it will show warning but continue when the specified track does not exist in the input file.

**Comment by warrex1979** [comment]
Thank you! I do not know if there are other options that can unnecessarily lead the encode to fail (H264 only options if used with HEVC for example) but this is all I needed.

Thank you so much for all your work and being so responsive to the input given here!

Closed.
