### ISSUE TITLE
nvenc raises error when specify "--ref 16  --profile auto" in h264 vbr mode.

### ISSUE THREAD

**Issue by AceCLee** [rigaya/NVEnc#208]
cmd: `--codec h264 --vbr/vbrhq xxx --ref 14~16  --profile auto`
nvenc output:

> nvenc : Failed to Initialize the encoder
> nvenc : .: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)

when ref is less than 14, it works fine.

and `--codec h264 --vbr/vbrhq xxx --ref 14~16 `  also works fine.

**Comment by rigaya** [comment]
This seems to be (again) a max bitrate problem but this is wierd.

"--profile auto" lets the NVENC SDK to select the suitable H.264 profile. Generally, it should be high profile for H.264.

H.264 1080p ref=16 should be H.264 Level 5.1, max bitrate should be 240000kbps for main profile, and 300000kbps(=240000 x 1.25) for high profile.

These are the result I've tested.

(1) ERR: -c h264 --vbr/vbrhq xxx --ref 16 --profile auto
(2) OK: -c h264 --vbr/vbrhq xxx --ref 16 --profile auto --max-bitrate 288000
(3) ERR: -c h264 --vbr/vbrhq xxx --ref 16 --profile auto --max-bitrate 290000
(4) OK: -c h264 --vbr/vbrhq xxx --ref 16 --profile high
(5) OK: -c h264 --vbr/vbrhq xxx --ref 16 --profile high --max-bitrate 288000
(6) ERR: -c h264 --vbr/vbrhq xxx --ref 16 --profile high --max-bitrate 290000

Well, it's hard to understand this behavior of NVENC SDK.

Actually, I don't want to go into this further, because it's hard to understand the rule when the NVENC SDK (or the driver) will return the error from the results above. Furthermore, it is very easy to avoid this, please just remove "--profile auto" or use "--profile high".

**Comment by AceCLee** [comment]
OK. I get it. Thanks for reply.
