### ISSUE TITLE
--level

### ISSUE THREAD

**Issue by djrooli** [rigaya/NVEnc#214]
Hello!

I always use Nvenc with no --level option (auto mode). I have video files with level 5.0 and above.
I wanted to convert the video over with --vpp-pad as my ****ty Panasonic TV doesn't have aspect ratio setting, and I have set up --level 5.0 and it did not work, I've had a level 4.1 result.
I did not notice any difference as there's only 8 bit LCD-s on the market, but I'm curious for the future.
Anybody had experience with this?

Thank you.

**Comment by djrooli** [comment]
I've read the level selection is always auto and the level I set is the max. level. Can it be?

**Comment by jdsanchezii** [comment]
The level metadata present in a video file only exists to tell the playback device what the minimum requirements are in order to play back that file/stream. Setting it does not affect the quality or any other attributes of the video. However, there are certain limitations for each level and the video should not be encoded outside the boundaries of the selected level in order to stay compliant with the selected level (i.e. h265 main@4.1@high can only support up to 48Mbps max bitrate). Also, you must ensure that your playback device supports the level you're using in your media. Otherwise it will not play.
