### ISSUE TITLE
Streams copy and disposition

### ISSUE THREAD

**Issue by kliffgomel** [rigaya/NVEnc#235]
Use source mkv file with 4 audio streams and 2 subtitle streams.
I want to copy the 3rd and 2nd audio tracks exactly in this order, and assign the 3rd source track in the output file to the default track. I also want to copy the 1st subtitle track to the output file and set it as the default track with the flag forced.
For this in ffmpeg I would do this:
-map 0:a:2 -map 0:a:1 -map 0:s:0
-disposition:a:0 default -disposition:s:0 default+forced

Using nvencc I do this:
--audio-copy 3,2 --sub-copy 1 (as I understand it, the tracks in the original file are numbered starting with 1 when copying)
This copies the 3rd and 2nd audio tracks and the 1st subtitle track, but the audio tracks are copied in order in the original file, i.e. in the output file they will follow as the 2nd and 3rd track of the original file.
Oddly, it was expected, as in ffmpeg, that tracks would follow in the order they were indicated on the command line.

If I try now to specify the desired attributes of these tracks in this way:
--audio-copy 3,2 --audio-disposition 3:default (or 0:default or 1:default - can 't find examples for nvencc how tracks are numbered in the output file) --sub-copy 1 --sub-disposition 1:default+forced
And as a result, I get all 4 original audio tracks and 2 subtitle tracks in the output file without applying the attributes I specify.

I can 't understand - is it a bug or did I just not correctly specify the program parameters?

**Comment by rigaya** [comment]
I have made NVEncC to ignore the order of the options for simplicity, therefore it is not possible to flip the order of 2nd and 3rd audio track. New option --audio-disposition has been added in NVEnc 5.02 so that we are at least able to set the default track.

I feel that the options you are using are not as the app is expecting, would you please test the option below? If this does not work, there must be a bug somewhere...

--audio-copy 2,3 --audio-disposition 3?default --sub-copy 1 --sub-disposition 1?default,forced

**Comment by kliffgomel** [comment]
Yes it works!
Thank you for the clarification.
