### ISSUE TITLE
Usage of --avsync forcecfr

### ISSUE THREAD

**Issue by jdobbs1954** [rigaya/NVEnc#327]
I'm experiencing an issue in which, when I try to use "--avsync forcecfr" in order to convert a VFR source to CFR, I am getting warnings "Big gap was found between 2 frames, avsync may be corrupted" -- and the audio/video is out of sync.   Can you explain this error and why I am getting it?   Why is there a limit on the distance between two frames in a VFR source?  Is there anything that can be done to get around this issue?

**Comment by rigaya** [comment]
It's just as it can be read, there was a large interval between 2 frames -- more than 8 frames interval when converted CFR.

The limitations is simply because I have not thought to be used against a situation like this. I have only used this when converting 24～30fps VFR to 30fps CFR. I haven't checked yet, but I think it is be possible to remove this limitation.

**Comment by jdobbs1954** [comment]
Thanks.   If you could look at it, it would be appreciated.   There are a lot of VFR sources out there lately, and I'm getting that error in almost all of the ones I've tried.   I'm converting them to CFR so they are compliant with Blu-Ray and DVD standards.  I'm guessing the issue usually occurs when there is a black screen (like a fade out to commercial break in a TV series), which can last for a second or more.

**Comment by jdobbs1954** [comment]
Any update as to whether you can remove the 8 frame interval limitation?

Thanks.

**Comment by rigaya** [comment]
The limitation of maximum frames to be inserted between two VFR frames is now relaxed from 8 to 1024 in NVEnc 5.30.

**Comment by rigaya** [comment]
I’ll close this issue as the problem should have been fixed.
