### ISSUE TITLE
problem with level

### ISSUE THREAD

**Issue by Selur** [rigaya/NVEnc#4]
There seems to be some problem with the level 
using NVEncC (x64) 3.02 with:
`"ffmpeg.exe" -y -threads 6 -r 24000/1001 -analyzeduration 100M -probesize 100M -i "F:\TestClips&Co\test.avi" -map 0:0 -an -sn  -vsync 0  -pix_fmt yuv420p  -f yuv4mpegpipe - | "NVEncC.exe" --y4m -i - --fps 23.976 --codec h264 --profile high --level 3 --sar 1:1 --lookahead 16 --cqp 20:23:25 --gop-len 0 --bframes 3 --ref 3 --mv-precision Q-pel --cabac --deblock --videoformat undef --fullrange --colorprim undef --transfer undef --colormatrix bt709 --output "h:\Output\test.264"`
I get:
> Failed to Initialize the encoder
.: 8 (NVENC indicates that one or more of the parameter passed to the API call is invalid.)

the source is 23.976fps with 640x352 so level 3 (https://de.wikipedia.org/wiki/H.264#Level) should be enough. 

GPU used is a Geforce GTX 980 Ti with NVIDIA driver version 376.33.

Using '--level 4' and '--level 5'  works, using '--level 3.1' doesn't. Seems like the level isn't properly indicated to the encoder.

**Comment by rigaya** [comment]
Thank you for the report. I was able to reproduce the problem with GTX1060, even with 320x240, 15fps.

This is caused because the default max bitrate is always set to 17500kbps by default.

I'll change this behavior in next version, chaging the default max bitrate automatically depending on the movies resolution and fps.

You can avoid this problem in current version by setting max bitrate to lower value, using --max-bitrate option.

**Comment by Selur** [comment]
Thanks.
Since I used --cqp I assumed --max-bitrate wouldn't have any effect. :)
-> looking forward for the next release.

**Comment by rigaya** [comment]
I have uploaded NVEnc 3.03 fixing this issue.
