### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by x901c963s** [rigaya/NVEnc#406]
It's not really a problem, but I need your help with something important to me.
NVEnc really does my job great. Hardware continues to use it as a solver, but although it uses the graphics card completely, I think it consumes my computer's processor to read or write data from the disk. I need your help with this because my processor is so weak! The reason I can't upgrade my processor is because my motherboard supports it. I have to use a Bitcoin motherboard because I can use 8 graphics cards at the same time... Is there a formula to minimize CPU consumption? Or what methods should I try to minimize it?

**Comment by rigaya** [comment]
In order to reduce CPU usage in NVEnc, I think items below can be tried.

1. Use --avhw (hw decoder) if possible.
1. Add "[--cuda-schedule](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--cuda-schedule-string) sync" option
  This changes the behavior of the CPU when waiting for GPU task completion. By using "sync", CPU thread will sleep till the GPU task finishes. Performance might decrease, but will reduce CPU utilization.
1. Use "--audio-copy" instead of "--audio-codec" if possible.
1. Add "[--output-thread](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--output-thread-int) 0"
  Disable using separate output thread, which might slightly reduce CPU usage. (actually impact should be low)
