### ISSUE TITLE
NVencC64 doesn't recognize Chinese characters in avisynth.

### ISSUE THREAD

**Issue by Sofronio** [rigaya/NVEnc#47]
I am using NVEncC 4.01 (r759) x64 version, the input file is a avisynth file, the first line looks like this
`LoadPlugin("E:\Bilibili\Tools\小丸工具箱七七版rev117\tools\avsfilter\VSFilter.DLL")`
and when I run NVencC, it reports red error like this:
```
avs: invalid clip.
avs: Cannot load file 'E:/Bilibili/Tools/
```
which seems ignored the Chinese characters.
The avs file is an ANSI file. I have changed the avs file into UTF-8, and it said it's not supported.

BTW, the x86 version works fine with the same avisynth file.

**Comment by rigaya** [comment]
Avs file should be ANSI file (not UTF-8), and parsing of avs file is done by Avisynth itself, and not by NVEncC. Also, using Japanese (or Chinese) characters in avs file works out fine in my system, so I'm not able to figure out the exact reason of the problem.

As it seems to be something due to char code, I have explicitly set locale of NVEncC to system default in NVEnc 4.02. Hope it makes some difference...

**Comment by pwacooijmans** [comment]
maybe avisynth++ might work http://avisynth.nl/index.php/AviSynth%2B

**Comment by rigaya** [comment]
I also think using Avisynth+ might hadle Chinese characters better.
