### ISSUE TITLE
NVEnc 7.31 using downloaded tar.gz , Directory cppcodec is empty

### ISSUE THREAD

**Issue by Shanghai-Tom** [rigaya/NVEnc#519]
This is not an urgent issue, I could not compile from the tar.gz but using git clone to compile  was successful.

On Linux:

Compilation error:

NVEnc 7.31 using download from (https://github.com/rigaya/NVEnc/archive/refs/tags/7.31.tar.gz)

NVEncCore/rgy_input_avcodec.cpp:38:10: fatal error: **cppcodec/base64_rfc4648.hpp: No such file or directory**
```
   38 | #include <cppcodec/base64_rfc4648.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
compilation terminated.
make: *** [makefile:35: NVEncCore/rgy_input_avcodec.cpp.o] Error 1

**Note:**

Compilation and installation from git clone https://github.com/rigaya/NVEnc --recursive completes with no errors.

```
./nvencc --check-hw
NVEnc (x64) 7.31 (r2580) by rigaya, Sep  9 2023 19:58:25 (gcc 11.4.0/Linux)
  [NVENC API v12.1, CUDA 12.1]
 reader: raw, y4m, avsw, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1, MPEG1, MPEG4, AV1]
#0: NVIDIA GeForce GTX 1070 (1920 cores, 1784 MHz)[PCIe3x16][530.30]
Avaliable Codec(s)
H.264/AVC
H.265/HEVC
```

**Comment by rigaya** [comment]
Actually, this is not an issue, and a expected behavior.

Some of the source code such as cppcodec comes not from by my repository, but from other repositories as submodules. Therefore, it is required to also download these submodules, and this is why it is recommended to download the source code by git clone with --recursive.
https://github.com/rigaya/NVEnc/blob/master/Build.en.md#7-build-nvencc

tar.gz made by default in github does not include submodules, so this is why you are getting the error. You can download submodule sources manually, but "git clone" is much more simpler.

**Comment by Shanghai-Tom** [comment]
Thank you for your kind explanation, I will use git for future downloads.
