### ISSUE TITLE
avsw: Unknown input option: framerate=30000/1001, ignored

### ISSUE THREAD

**Issue by rainman74** [rigaya/NVEnc#573]
`--fps 30000/1001` and `--fps 29.970` leads to an error message, but is apparently converted correctly after all.

![image](https://github.com/rigaya/NVEnc/assets/16306963/c952d5db-da6d-4feb-8de7-4fbc8f76cfe5)

**Comment by rigaya** [comment]
As written in the manual, [--fps](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--fps-intint-or-float) is valid only for raw input, and otherwise it will be ignored or only treated as a hint.

There will be the message but is expected behavior.

Also, the fps shown on the log will change but is expected behavior.

I think you need not to set --fps for avsw reader, as framerate will be taken from the input file.

**Comment by rainman74** [comment]
> As written in the manual, [--fps](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--fps-intint-or-float) is valid only for raw input, and otherwise it will be ignored or only treated as a hint.
> 
> There will be the message but is expected behavior.
> 
> Also, the fps shown on the log will change but is expected behavior.
> 
> I think you need not to set --fps for avsw reader, as framerate will be taken from the input file.

Exactly not. The original file is 25.0 fps and the --fps specification is not ignored, but the file is correctly converted to 29.97 fps, even though it is not raw.

So I think the current behavior is good, I was just disturbed by the apparently wrong hint.

**Comment by rigaya** [comment]
The message has been removed, I’ll close the issue now.
