### ISSUE TITLE
Versions 7.49 and 7.50 are much slower than 7.48

### ISSUE THREAD

**Issue by rainman74** [rigaya/NVEnc#580]
Version 7.49 and 7.50 are much slower than 7.48.

Update: Performance drop with --tune hd --tf-level 0 --lookahead 32 --lookahead-level auto ~ 50% !

I'm back to 7.48.

**Comment by Jigsawbg** [comment]
As of version 7.49, 3 new encoding options have been implemented. The options give an excellent result in terms of encoding quality at HEVC/h265. The options are:
```
--tune
--tf-level
--lookahead-level
```
If you want the performance before 7.49, use them like this:
```
--tune lowlatency
--tf-level 0
--lookahead-level 0
```
Lower performance is primarily due to --tf-level and --tune uhq.
If you want maximum quality, then use:
```
--tune uhq --> only supported by Ampere architecture.
--tf-level 4
--lookahead-level auto
```
But the performance is greatly reduced... No complete happiness :)
IMHO that since I've been using nvencc64(7.41) this change is the best!

**Comment by quamt** [comment]
Screenshot
------
![image](https://github.com/rigaya/NVEnc/assets/64795789/ac1b179c-fa89-49f6-999d-36d918bb01b5)
------




There is no auto for the lookaheadlevel.

```
--lookahead-level <int> [HEVC]
Set level of lookahead, higher level may improve quality at the expense of performance. (0 - 3, default = 0)
```

**Comment by Jigsawbg** [comment]
Interesting... There is probably some confusion because 7.50 works with auto. Initially
in version 7.49 the default value was auto and I personally still use it that way. I read it from Rigaya's post #577(clossed issue).
```
The performance drop was due to the new --lookahead-level option added in NVEnc 7.49, defaulted to auto.

I've changed the default to 0 in Nvencc 7.50, and will remove the performance drop.
```
As we can see from the same post, in version 7.50 it changes the `default value to 0`, but this does not mean that `auto` is removed, just that the value is changed. 
And yes, you are right that there is no `auto` value in the description. 
But I think it's a mistake in description, I hope it's a mistake and the value hasn't been removed. The fact that it still works like this makes me think it's relevant.

**Comment by quamt** [comment]
I tested it with a few files on auto, and it always shows as follows:
`Lookahead      on, 32 frames, Adaptive I, B Insert`

Setting 1, 2 or 3 shows as follows:
```
Lookahead      on, 32 frames, Level 1, Adaptive I, B Insert
Lookahead      on, 32 frames, Level 2, Adaptive I, B Insert
Lookahead      on, 32 frames, Level 3, Adaptive I, B Insert
```

Setting 0 shows as follows:
`Lookahead      on, 32 frames, Level 0, Adaptive I, B Insert`

Auto doesn't show anything in the info line of Lookahead during the encoding.

**Comment by Jigsawbg** [comment]
```
Tuning Info    uhq
Lookahead      on, 32 frames, Adaptive I, B Insert
```

Yes, there are no visible signs of `auto` being used at all.

But just because nvencc64 didn't return any error, I thought it was working. I really hope Rigaya didn't remove this option because I don't see any logical reason for it. Changing the default value does not conflict with the other possible options that NVIDIA has provided.
I hope Rigaya will clarify the exact lookahead-level options. If he did remove the `auto` option, I hope he will bring it back.

**Comment by rigaya** [comment]
--lookahead-level accepts "auto" and level will not be shown in the log, but it seems to be the same as "3" at this time.

**Comment by rainman74** [comment]
> --lookahead-level accepts "auto" and level will not be shown in the log, but it seems to be the same as "3" at this time.

Wouldn't it be better to leave the parameters in the default settings so that performance is not immediately reduced by 50%? If you then want higher quality, you can tune it.

**Comment by rigaya** [comment]
> Wouldn't it be better to leave the parameters in the default settings so that performance is not immediately reduced by 50%? If you then want higher quality, you can tune it.

Yes, so NVEnc 7.50 has changed default of --lookahead-level from "auto" to "0", which will result the same performance of NVEnc 7.48 and before.
