### ISSUE TITLE
SDR to HDR10

### ISSUE THREAD

**Issue by Bandid0** [rigaya/NVEnc#601]
Greetings.
Is it possible to convert SDR video to HDR10 with the new Nvenc function --vpp-ngx-truehdr?
That is what I have tried and in the resulting video mediainfo does not recognize it as HDR, specifically I have used this configuration.
--vbr 10000 --codec h265 --preset quality --output-depth 10 --tier high --multipass 2pass-full --vpp-resize --vpp-ngx-truehdr --colormatrix bt2020nc --colorprim bt2020 -- transfer smpte2084 --output-res 3840x2160.

**Comment by qwe7989199** [comment]
Could you post the mediainfo here?
Maybe it is just a duplicated question and could be answered by the comment originally posted by @rigaya in https://github.com/rigaya/NVEnc/issues/550#issuecomment-2198500119

**Comment by Bandid0** [comment]
> ¿Podrías publicar la información de los medios aquí? Tal vez sea solo una pregunta duplicada y podría responderse con el comentario publicado originalmente en [#550 (comentario)](https://github.com/rigaya/NVEnc/issues/550#issuecomment-2198500119)


It is certainly the same question and it is already answered, I did not see it. thank you

**Comment by qwe7989199** [comment]
> > ¿Podrías publicar la información de los medios aquí? Tal vez sea solo una pregunta duplicada y podría responderse con el comentario publicado originalmente en [#550 (comentario)](https://github.com/rigaya/NVEnc/issues/550#issuecomment-2198500119)
> 
> It is certainly the same question and it is already answered, I did not see it. thank you

HDR10 refers to HDR with static metadata, whereas PQ10 is an HDR10 format without any metadata.  
In the case of PQ10, mediainfo will not explicitly contain the 'hdr' string, but the video is still HDR.
Hope the introduction of the PQ10 concept can make the issue clearer.

[Related link](https://en.wikipedia.org/wiki/HDR10#cite_note-:42-3:~:text=PQ10%20refers%20to%20an%20HDR10%20format%20which%20does%20not%20include%20any%20metadata.%5B3%5D)

**Comment by rigaya** [comment]
@qwe7989199 Thank you for sharing the comment at #550 !

I also think that MediaInfo will not recognize the file as HDR10 as it lacks metadata (like mastering display), but still SDR2HDR tone mapping has been done.

**Comment by NeedsMoar** [comment]
You can always add the mastering data.  The truehdr thing converts to bt2020 (check the source) so those are the primaries you need.

--master-display "G(8500,39850)B(6550,2300)R(35400,14600)WP(15635,16450)L(10000000,1)"

MaxCLL and MaxFALL aren't known until the video is encoded but I always analyze with madvr afterwards and use the analysis to add dolby vision metadata with dovi_tool, and the true values from that will be used instead;  the correct thing to do if they're unknown is to set both to 0 so they won't be used incorrectly:

--max-cll 0,0

Then add in the remainder (the chromaloc is standard for HDR10):
 --chromaloc 2 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --colorrange limited 

Mediainfo will show something like this: 
```
Format/Info : High Efficiency Video Coding 
Format profile : Main 10@L5@Main 
HDR format : SMPTE ST 2086, HDR10 compatible 
Codec ID : hvc1 
Codec ID/Info : High Efficiency Video Coding 
Duration : 9 min 35 s 
...
Chroma subsampling : 4:2:0 (Type 2) 
...
Color range : Limited 
Color primaries : BT.2020 
Transfer characteristics : PQ 
Matrix coefficients : BT.2020 non-constant 
Mastering display color primaries : BT.2020 
Mastering display luminance : min: 0.0001 cd/m2, max: 1000 cd/m2 
Maximum Content Light Level : 1000 cd/m2 
Maximum Frame-Average Light Level : 300 cd/m2 
Codec configuration box : hvcC 
```

Technically the mastering luminance is incorrect, but in reality it doesn't seem to matter.  I've yet to see a single UHD disk that didn't use one of the "default" 3 values...  it's either BT2020 primaries with the above luma, Display P3 with the above luma, or display P3 with Mastering display luminance : min: 0.0050 cd/m2, max: 4000 cd/m2 which is a bit ironic since I don't think any mastering display with a max luminance that high existed for any price at the time some of the movies were released.  I don't think any do right now, really.  There's no point in mastering for a target nobody else can see.  It's sort of like the higher end photography oriented monitors I used for years that were calibrated to AdobeRGB for printing...  still had to upload sRGB to the web because most monitors didn't even have "real" 8-bit color at the time, let alone the 10-bit AdobeRGB requires.   Just 6-bit + FRC.  That's slowly been changing, now it's the 10-bit panels that are mostly 8-bit + FRC unless they're OLEDs (or expensive, as usual).

**Comment by Bandid0** [comment]
thank you so much
